language: go
go:
- 1.1
- 1.2
- 1.3
- 1.4
- tip
notifications:
  hipchat:
    rooms:
      secure: F4aENVhJ7UXTc9a+lNaosYVp7/Os/ALyEJud4TuQyBTUgyqP2VUtmAm9tqLDnDwcDMOKowLIYRmkG1DZzDydyBHIItFwvPu2/s1wf/0eYm6Hin12A76fspWVdiM29B1C87D0R/zDzFEHla2MEtHNT2GPL2sEIbLMAODbtSKd7Mw=
