language: go
go:
- 1.0
- 1.1
- 1.2
- tip
notifications:
  hipchat:
    rooms:
      secure: R7Ez6SHHx2Ui6sqgPMiYuLuhEbxDaq7A2yhgw925wjYpqkIiOh6j6nHXkIHj0vGUMowWlvZCfGX8dVrq8PhjSm46rkN1sJXraqMlQqvIOiHooeIfDQdt+aVlm8XsJwXRkqkS+ghQBAsqfwz9mkBmNE7M9Ue0tuVBRw4e4O0/DLw=
