language: go
go:
- 1.0
- 1.1
- 1.2
- tip
notifications:
  hipchat:
    rooms:
      secure: qbCaZZC9r0k/xCxSR3L9UqRD9oz9+cftWmItQ+IkadppR6Ga/8cW/3NUY//lMnaNOyE2mi2qt34IyweFU2qUA4QSs55meEh46dBbqwSVGUIsv1L5VQ8LvP6wxvWYbEh1J4J01fLpQ8uSDfqD0tRHmfHMqHVsgG7mRlFBjDg/r0o=
